### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by inx7** [microsoft/msticpy#112] opened 2020-10-16 09:55 UTC
**Describe the bug**
Running https://github.com/Azure/Azure-Sentinel-Notebooks/blob/master/TroubleShootingNotebooks.ipynb in Azure ML got following error during installation of msticpy ([full installation log](https://github.com/microsoft/msticpy/files/5390653/msticpy.error.txt)):
```
Collecting iniconfig
  Using cached iniconfig-1.1.1.tar.gz (8.1 kB)
  Installing build dependencies ... - error
  ERROR: Command errored out with exit status 1:
   command: /anaconda/envs/azureml_py36/bin/python /anaconda/envs/azureml_py36/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-k0pbth3e/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=41.2.0' wheel 'setuptools_scm>3'
       cwd: None
```
Python version: 3.6.9

**To Reproduce**
1. Run https://github.com/Azure/Azure-Sentinel-Notebooks/blob/master/TroubleShootingNotebooks.ipynb in Azure ML Notebooks
![error](https://user-images.githubusercontent.com/33892142/96244160-5e8da780-0fae-11eb-9526-765be1ca460f.jpg)

**Comment by ianhelle** [comment] 2020-10-20 17:15
@inx7 - thanks for the detailed report. 
The cause of this was a bit obscure:
- at base it is because of an incompatible library that Azure ML have on their compute images - enum34 
  (which is really meant to be only used on Python < 3.6). The problem being that pandas-ml package installs this by default.
- the problem was surfaced by an accidental dependency of the new(is) Virus Total libraries (by mistake, they were including
  a bunch of test packages in the production release dependencies. I heard from them this morning that this had
  been fixed as of vt-py 0.6.3.
- We're trying to setup a better automated test mechanism for Azure ML to try to catch things like this before hitting the presses.

Thanks again for the report.

**Closed by ianhelle** 2020-10-20 17:15 UTC
