### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by mark-kramtest** [microsoft/msticpy#808] opened 2024-12-04 09:38 UTC
**Describe the bug**
Getting TypeError [TypeError: get() got an unexpected keyword argument 'proxies'] when running:

_# Connect to Microsoft Sentinel with our QueryProvider and config details
qry_prov.connect(ws_config)_

**To Reproduce**

New AML compute instance. Followed all steps to setup msticpy configuration.
config files present and properly loaded. All steps passing besides mentioned above.

Other compute instance with same settings works properly.

**Expected behavior**
Successfull connection to Sentinel provider.

**Screenshots and/or Traceback**

![Image](https://github.com/user-attachments/assets/ccdda28c-deca-448b-8341-92e09f48a4df)

**Environment (please complete the following information):**

- Python Version: [3.10]
- OS: [Ubuntu Linux 24.10.18 ]
- Python environment: [Cloud Azure ML]
- MSTICPy Version: [2.14.0]

**Comment by agahen** [comment] 2024-12-05 08:34
Looks like related to deprecation of 'proxies', ref: https://github.com/encode/httpx/pull/2879

**Comment by ianhelle** [comment] 2024-12-05 17:24
Thanks @agahen for filing the issue and @mark-kramtest for diagnosing the cause.
I will update msticpy to replace the use of the deprecated `proxies` parameter

**Comment by ianhelle** [comment] 2024-12-13 20:21
This should be fixed in the current release 2.15.0

**Closed by ianhelle** 2024-12-13 20:21 UTC
Labels: bug
